buy_lotto_645:
  fields:
    game_1:
      required: true
      selector:
        text:
    game_2:
      required: false
      selector:
        text:
    game_3:
      required: false
      selector:
        text:
    game_4:
      required: false
      selector:
        text:
    game_5:
      required: false
      selector:
        text:
